/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as WalletPnlRouteImport } from './routes/wallet-pnl'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as NarrativesRouteImport } from './routes/narratives'
import { Route as MemeOfTheDayRouteImport } from './routes/meme-of-the-day'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoinsRouteImport } from './routes/coins'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPumpfunLatestRouteImport } from './routes/api/pumpfun/latest'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletPnlRoute = WalletPnlRouteImport.update({
  id: '/wallet-pnl',
  path: '/wallet-pnl',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const NarrativesRoute = NarrativesRouteImport.update({
  id: '/narratives',
  path: '/narratives',
  getParentRoute: () => rootRouteImport,
} as any)
const MemeOfTheDayRoute = MemeOfTheDayRouteImport.update({
  id: '/meme-of-the-day',
  path: '/meme-of-the-day',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinsRoute = CoinsRouteImport.update({
  id: '/coins',
  path: '/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPumpfunLatestRoute = ApiPumpfunLatestRouteImport.update({
  id: '/api/pumpfun/latest',
  path: '/api/pumpfun/latest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/coins': typeof CoinsRoute
  '/dashboard': typeof DashboardRoute
  '/meme-of-the-day': typeof MemeOfTheDayRoute
  '/narratives': typeof NarrativesRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/wallet-pnl': typeof WalletPnlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pumpfun/latest': typeof ApiPumpfunLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/coins': typeof CoinsRoute
  '/dashboard': typeof DashboardRoute
  '/meme-of-the-day': typeof MemeOfTheDayRoute
  '/narratives': typeof NarrativesRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/wallet-pnl': typeof WalletPnlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pumpfun/latest': typeof ApiPumpfunLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/coins': typeof CoinsRoute
  '/dashboard': typeof DashboardRoute
  '/meme-of-the-day': typeof MemeOfTheDayRoute
  '/narratives': typeof NarrativesRoute
  '/pulse': typeof PulseRoute
  '/settings': typeof SettingsRoute
  '/trending': typeof TrendingRoute
  '/wallet-pnl': typeof WalletPnlRoute
  '/watchlist': typeof WatchlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pumpfun/latest': typeof ApiPumpfunLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/coins'
    | '/dashboard'
    | '/meme-of-the-day'
    | '/narratives'
    | '/pulse'
    | '/settings'
    | '/trending'
    | '/wallet-pnl'
    | '/watchlist'
    | '/api/chat'
    | '/api/pumpfun/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/coins'
    | '/dashboard'
    | '/meme-of-the-day'
    | '/narratives'
    | '/pulse'
    | '/settings'
    | '/trending'
    | '/wallet-pnl'
    | '/watchlist'
    | '/api/chat'
    | '/api/pumpfun/latest'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/coins'
    | '/dashboard'
    | '/meme-of-the-day'
    | '/narratives'
    | '/pulse'
    | '/settings'
    | '/trending'
    | '/wallet-pnl'
    | '/watchlist'
    | '/api/chat'
    | '/api/pumpfun/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CoinsRoute: typeof CoinsRoute
  DashboardRoute: typeof DashboardRoute
  MemeOfTheDayRoute: typeof MemeOfTheDayRoute
  NarrativesRoute: typeof NarrativesRoute
  PulseRoute: typeof PulseRoute
  SettingsRoute: typeof SettingsRoute
  TrendingRoute: typeof TrendingRoute
  WalletPnlRoute: typeof WalletPnlRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPumpfunLatestRoute: typeof ApiPumpfunLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet-pnl': {
      id: '/wallet-pnl'
      path: '/wallet-pnl'
      fullPath: '/wallet-pnl'
      preLoaderRoute: typeof WalletPnlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narratives': {
      id: '/narratives'
      path: '/narratives'
      fullPath: '/narratives'
      preLoaderRoute: typeof NarrativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meme-of-the-day': {
      id: '/meme-of-the-day'
      path: '/meme-of-the-day'
      fullPath: '/meme-of-the-day'
      preLoaderRoute: typeof MemeOfTheDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coins': {
      id: '/coins'
      path: '/coins'
      fullPath: '/coins'
      preLoaderRoute: typeof CoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pumpfun/latest': {
      id: '/api/pumpfun/latest'
      path: '/api/pumpfun/latest'
      fullPath: '/api/pumpfun/latest'
      preLoaderRoute: typeof ApiPumpfunLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CoinsRoute: CoinsRoute,
  DashboardRoute: DashboardRoute,
  MemeOfTheDayRoute: MemeOfTheDayRoute,
  NarrativesRoute: NarrativesRoute,
  PulseRoute: PulseRoute,
  SettingsRoute: SettingsRoute,
  TrendingRoute: TrendingRoute,
  WalletPnlRoute: WalletPnlRoute,
  WatchlistRoute: WatchlistRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPumpfunLatestRoute: ApiPumpfunLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
